---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mariadb-ssd"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/mariadb"
---