---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nextcloud-data"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "150Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/backup/nextcloud"
---