---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nextcloud-ssd"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "100Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/nextcloud"
---