---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mariadb-master"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mariadb/master"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "data-my-release-mariadb-slave-0"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: "data-my-release-mariadb-slave-0"
  hostPath:
    path: "/mnt/mariadb/slave"
---
