---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mariadb-master"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mariadb/master"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mariadb-slave"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mariadb/slave"
---