---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config
  labels:
    app: pihole
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "500Mi"
---