---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "mariadb-galera"
  name: "mariadb-galera-master"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "50Gi"
---
