---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mariadb-galera-master"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "50Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mariadb-galera/master"
---
